### ISSUE TITLE
refactor(lsp-ingress): reserve control processing and return typed ordinary admission outcomes

### ISSUE THREAD

**Issue by EffortlessSteven** [EffortlessMetrics/perl-lsp-swarm#10480]
Parent admission controller: #9505
Framework controller: #7384
Checked train: #10360
Messages and routing: #9636 / #7010 / #7610 / #9503
Scheduler kernel: #9643
Incoming request ownership: #7098
Lifecycle authority: #7390 / #9647
Mutation-failure successor: assigned by #9505

## One-PR result

Make the decoded-message ingress loop remain responsive to cancellation, responses, and lifecycle control while ordinary application work is saturated. This PR owns **routing and admission disposition only**. It does not implement byte-accounting primitives, mutation-failure recovery, request terminal arbitration, or outbound delivery.

## Problem

The current serving path can await ordinary read/mutation queue admission before reading the next frame. A full ordinary lane can therefore delay observing a later cancellation, client response, shutdown, or transport failure. Conversely, simply bypassing every lifecycle message would violate causal ordering where an accepted earlier mutation must remain ordered before shutdown.

## Objective

Introduce one language-neutral ingress authority:

```text
decoded IncomingMessage
  ├─ Response      → reverse-response router, never application dispatch
  ├─ Control       → reserved prompt route
  ├─ Lifecycle     → reserved admission with declared ordering/barrier
  └─ Application   → bounded ordinary admission
```

The ingress loop must not block on an ordinary application queue before it can observe later control traffic.

## Scope

- Add one typed admission result equivalent to:

```text
Admitted { work identity, reservation }
RejectedOverload
RejectedLifecycle
RejectedUnknownRoute
ConnectionClosing
MutationAdmissionFailed
```

- Route incoming responses directly to #7010 before application classification.
- Give cancellation and connection-control messages a bounded reserved path that ordinary reads cannot consume.
- Give lifecycle work reserved admission while preserving its declared mutation/lifecycle barrier; prompt admission does not mean illegal reordering.
- Use fail-closed route/work facts from #7610/#9503. Unknown work never inherits read concurrency.
- Make ordinary request/read/mutation admission nonblocking from the frame-reader’s perspective.
- Preserve request ID and message identity through overload/rejection so #7098 and outbound owners can settle the correct subject.
- Return a typed mutation-admission failure to the coherence owner; never log and drop a state-changing notification.
- Keep queue capacity/accounting implementation behind the dedicated limit leaf.
- Keep exact overload wire response and output failure with request/delivery owners.

## Negative controls

Fail when:

- a full read lane prevents a later `$/cancelRequest` from being observed;
- an incoming client response enters application dispatch;
- ordinary traffic consumes all control capacity;
- prompt lifecycle admission reorders ahead of an already accepted required mutation barrier;
- unknown/custom work defaults to read;
- an overloaded request loses its numeric/string ID;
- a state-changing notification is silently dropped;
- the ingress module imports Perl/provider/workspace policy;
- admission success is treated as application or response success.

## Tests

Use deterministic barriers:

- fill ordinary read admission, then observe cancellation promptly;
- fill mutation admission, then observe client response and shutdown promptly;
- lifecycle work retains its required barrier ordering;
- overloaded numeric `1` and string `"1"` remain distinct;
- unknown route fails closed;
- mutation admission failure is surfaced exactly once;
- connection close wakes/settles blocked producers without leaking reservations;
- non-Perl synthetic application.

## Acceptance

- [ ] One ingress authority routes every decoded message kind.
- [ ] Ordinary saturation cannot hide cancellation, responses, or connection control.
- [ ] Lifecycle promptness preserves declared causal ordering.
- [ ] Ordinary admission outcomes are typed and identity-preserving.
- [ ] Mutations are never silently lost.
- [ ] Generic ingress has zero Perl/domain dependency.
- [ ] Following limit, mutation-coherence, request, and delivery leaves can consume the seam without reopening routing.

## Codex contract

Move ingress routing/admission only. Add the saturated-read-plus-cancel and incoming-response-bypass falsifiers first. Preserve message/request/barrier identity and stop before implementing budget arithmetic, mutation recovery, terminal arbitration, writer behavior, or public API.

## Non-goals

No output queue work, no request registry implementation, no mutation desynchronization policy, no lifecycle state-machine implementation, no provider behavior, and no package publication.

**Comment by EffortlessSteven** [comment]
## Codebase research update (parent orchestrator review, current main be157d759)

**Verdict: CONFIRMED — the scheduler already classifies control/lifecycle/mutation/read traffic, but ordinary ingress still awaits bounded queue admission; a full ordinary lane can therefore stop the frame reader before it observes later control traffic.** The issue's routing/admission gap is reachable in the current implementation.

### Verified current state
- `crates/perl-lsp-rs/src/runtime/serving.rs:71-103` — `serve_async` classifies each decoded `JsonRpcRequest`; control is handled inline (:80-86), but lifecycle/mutation awaits `sched.send_mutation(request).await` (:87-90) and read-only awaits `sched.send_read(request).await` (:92-95).
- `crates/perl-lsp-rs/src/runtime/scheduler.rs:331` — `QUEUE_CAPACITY` is 64; both channels are bounded at :447-448. The send methods use `mpsc::Sender::send(...).await` (`:512-528` mutation, `:537-558` read), so a saturated ordinary queue back-pressures the ingress loop.
- The current control fast path is therefore only effective while the ingress loop is still reading: once it is suspended in `send_read` or `send_mutation`, a later `$/cancelRequest`, response, shutdown, or transport-close message cannot be classified yet.
- The scheduler already preserves useful identity/freshness pieces (`mark_request_pending`, mutation sequence, read priority/dedup/freshness), so the fix belongs at the admission boundary rather than in individual providers.
- The current receiver is `JsonRpcRequest`, not an all-message enum; incoming client responses are not represented in this loop, so the issue's response-bypass requirement is a protocol-ingress expansion, not just a queue tweak.

### Assessment
- The issue's proposed typed admission outcomes and reserved control/lifecycle capacity are necessary. Replacing `.send().await` with a nonblocking/typed admission operation must also preserve request ID, mutation barrier, and pending-marker rollback on rejection; otherwise overload handling creates a second correctness bug.

### Suggested next slice
- (1) Introduce one ingress admission result over decoded message kinds, (2) reserve control/response capacity that ordinary queues cannot consume, (3) make ordinary admission return `RejectedOverload` rather than suspend the frame reader, (4) preserve numeric/string IDs and mutation sequence/barriers on every outcome, (5) add deterministic saturated-read-plus-cancel and incoming-response-bypass tests. Acceptance: ordinary saturation cannot hide control/response/lifecycle traffic; unknown routes fail closed; no state-changing message is silently dropped.
